apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
spec:
  selector:
    app: test-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
